package ru.citycore.gui;

public enum Route {
    HOME,
    PROFILE,
    CITY,
    CITY_DIRECTORY,
    CITY_APPLICATIONS,
    CITY_APPLICATION_DETAIL,
    CITY_MEMBERS,
    BUSINESS,
    BUSINESS_DETAIL,
    BUSINESS_PENDING,
    LICENSES,
    ECONOMY,
    HELP,
    MAYOR,
    GOVERNMENT,
    ADMIN,
    CITY_FOUNDATIONS_ADMIN,
    CITY_FOUNDATION_DETAIL,
    EMISSION,
    CONFIRM
}
